### ISSUE TITLE
CD機能が欲しい

### ISSUE THREAD

**Issue by Morichan** [Morichan/ec2-instance-starter#22]
GitHub Actionsを使って、タグ駆動でデプロイできるようなフローはあってもいいかも

**Comment by Morichan** [comment]
下記を参考に、シンプルなデプロイフローを作ってみました。
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-generating-example-ci-cd-others.html

以下のように作ればいけそうですが、動作確認が大変そうなので後はどなたかに任せます（未来の自分かもしれませんが）。

- `on.push.tags` に `*` は対応しているのか未確認
- `jobs.deploy.steps[2].users.aws-actions/setup-sam@v1` は、 `pipenv install --dev` でできるようにしたい
    - というかすべき
    - Pipfileの [dev] 欄に書けばいいはず
- `jobs.deploy.steps[4].with.role-session-name` の `prod-deployment` は何を指しているのか未確認
- `jobs.deploy.steps[5].run` の `sam deploy` ができるのか未確認

```yaml
name: CD

on:
  push:
    tags:
    - '*'

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STACK_NAME: ec2-instance-starter
  PIPELINE_EXECUTION_ROLE: ${{ secrets.SAM_DEPLOYMENT_ROLE }}
  CLOUDFORMATION_EXECUTION_ROLE: ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}
  ARTIFACTS_BUCKET: ${{ secrets.SAM_DEPLOYMENT_AFTIFACT_BUCKET }}
  IMAGE_REPOSITORY: ${{ secrets.SAM_DEPLOYMENT_IMAGE_REPOSITORY }}
  REGION: ${{ secrets.SAM_DEPLOYMENT_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Assume the prod pipeline user role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
        role-session-name: prod-deployment
        role-duration-seconds: 3600
        role-skip-session-tagging: true
    - name: Deploy to production account
      run: |
        pipenv lock --no-header --requirements > src/requirements.txt
        sam build
        sam deploy --stack-name ${STACK_NAME} \
          --template .aws-sam/build/template.yaml \
          --capabilities CAPABILITY_IAM \
          --region ${REGION} \
          --s3-bucket ${ARTIFACTS_BUCKET} \
          --image-repository ${IMAGE_REPOSITORY} \
          --no-fail-on-empty-changeset \
          --role-arn ${CLOUDFORMATION_EXECUTION_ROLE}
```
